### ISSUE TITLE
dont be gay

### ISSUE THREAD

**Issue by ToxicDevv** [dominikaaaa/hydrator#1]
gay is bad

**Comment by dominikaaaa** [comment]
What the hell was the purpose of this issue??? Did you just decide to check my profile on another repo and comment on another unrelated repo?????

**Comment by iBuyMountainDew** [comment]
Meme issue moments :p

**Comment by pol-y-mer** [comment]
i didnt know this repo was polymer brain code repo ive been trying to fix this issue for a while now! anybody got any progress?????
